// require("./examples/mCachingTut")
// require("./examples/promiseTut")
// require("./examples/asyncawaitTut")
// require("./examples/addTut")
// require("./examples/pizza-shop-ex")
// require("./examples/copyData")
// require("./CJS-Modules/iife")
// require("./CJS-Modules/dataFetch")
// require('./CJS-Modules/callback');
// require("./BuiltIn-Modules/path-m")
// require("./BuiltIn-Modules/event-m")
// require("./BuiltIn-Modules/fs-m")
// require("./BuiltIn-Modules/fs-promises-m")
// require("./BuiltIn-Modules/zlib-m")
// require("./BuiltIn-Modules/http-m")
// require("./examples/dynamicHTML/type1")
require("./examples/dynamicHTML/routing")