const path = require("node:path")

// console.log(path.basename(__dirname))
// console.log(__filename)
// console.log(path.parse(__filename))
// console.log(path.format(path.parse(__filename)))
// console.log(path.basename(__filename))
// console.log(path.extname(__filename))
// console.log(path.isAbsolute(__filename))
// console.log(path.isAbsolute(path.basename(__filename)))

// console.log(path.join("folder", "sub-folder", "file.ext"))
// console.log(path.join("folder", "//sub-folder", "file.ext"))
// console.log(path.join("folder", "/sub-folder", "../file.ext"))
// console.log(path.join(path.basename(__dirname), "data.json"))

console.log(path.resolve("folder", "sub-folder", "file.ext"))
console.log(path.resolve("folder", "//sub-folder", "file.ext"))
console.log(path.resolve("folder", "/sub-folder", "../file.ext"))
console.log(path.resolve(path.basename(__dirname), "data.json"))